version: '2.1'

services:

  yuo-db:
    container_name: yuo-db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  yuo-service:
    container_name: yuo-service
    build: ./
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@yuo-db:5432/yelp_us_out_dev
      - DATABASE_TEST_URL=postgres://postgres:postgres@yuo-db:5432/yelp_us_out_test
    depends_on:
      yuo-db:
        condition: service_healthy
    links:
      - yuo-db

  nginx:
    container_name: nginx
    build: ./nginx/
    restart: always
    ports:
      - 80:80
    depends_on:
      yuo-service:
        condition: service_started
    links:
      - yuo-service
